image: python:3.8.1

pages:
  stage: deploy
  script:
    # install packages
    - apt-get update && apt-get install software-properties-common && add-apt-repository http://archive.ubuntu.com/ubuntu/
    - apt-get install hledger

    # fetch protected input data
    - git clone https://rwev:${GITLABP}@gitlab.com/rwev/evix.dat.git
    - rm -r ./evix.dat/.git
    - mv ./evix.dat/.[!.]* ./

    # install additional pelican requirements
    - pip install -r requirements.txt
    - git clone https://gitlab.com/rwev/mesa.git
    - git clone --recurse-submodules https://gitlab.com/rwev/pelican-plugins.git

    # run pelican build process
    - invoke styles
    - make publish
  artifacts:
    paths:
      - public/
  only:
    - master
